SiteMarchand/Models/Enregistrement.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteMarchand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enregistrement
    {
        public Enregistrement()
        {
            this.Achat = new HashSet<Achat>();
            this.Composition_Disque = new HashSet<Composition_Disque>();
            this.Direction = new HashSet<Direction>();
            this.Interpréter = new HashSet<Interpréter>();
        }
    
        public int Code_Morceau { get; set; }
        public string Titre { get; set; }
        public int Code_Composition { get; set; }
        public string Nom_de_Fichier { get; set; }
        public string Durée { get; set; }
        public Nullable<int> Durée_Seconde { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public byte[] Extrait { get; set; }
    
        public virtual ICollection<Achat> Achat { get; set; }
        public virtual Composition Composition { get; set; }
        public virtual ICollection<Composition_Disque> Composition_Disque { get; set; }
        public virtual ICollection<Direction> Direction { get; set; }
        public virtual ICollection<Interpréter> Interpréter { get; set; }
    }
}

SiteMarchand/Controllers/EnregistrementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiteMarchand.Models;
using PagedList;

namespace SiteMarchand.Controllers
{
    public class EnregistrementsController : Controller
    {
        private Classique_WebEntities1 db = new Classique_WebEntities1();

        // GET: Enregistrements
        public ActionResult Index(string searchString, string currentFilter, string sortOrder, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DurationSortParm = String.IsNullOrEmpty(sortOrder) ? "duration_desc" : "";

            var enregistrement = db.Enregistrement.Include(e => e.Composition);

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            if (!String.IsNullOrEmpty(searchString))
            {
                enregistrement = db.Enregistrement.Include(e => e.Composition).Where(c => c.Titre.StartsWith(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    enregistrement = enregistrement.OrderByDescending(s => s.Nom_de_Fichier);
                    break;
                case "duration_desc":
                    enregistrement = enregistrement.OrderByDescending(s => s.Durée_Seconde);
                    break;
                default:
                    enregistrement = enregistrement.OrderBy(s => s.Nom_de_Fichier);
                    break;
            }

            int pageSize = 25;
            int pageNumber = (page ?? 1);
            return View(enregistrement.ToPagedList(pageNumber, pageSize));
        }

        // GET: Enregistrements/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enregistrement enregistrement = db.Enregistrement.Find(id);
            if (enregistrement == null)
            {
                return HttpNotFound();
            }
            return View(enregistrement);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SiteMarchand/Views/Enregistrements/Details.cshtml
@model SiteMarchand.Models.Enregistrement

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Enregistrement</h4>
   
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nom_de_Fichier)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom_de_Fichier)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Durée)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Durée)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Durée_Seconde)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Durée_Seconde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Extrait)
        </dt>

        <dd>
            @Html.Music(Model.Extrait)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Composition.Titre_Composition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Composition.Titre_Composition)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Code_Morceau }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SiteMarchand/Views/Enregistrements/Index.cshtml
@model PagedList.IPagedList<SiteMarchand.Models.Enregistrement>

@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@using (Html.BeginForm("Index", "Enregistrements", FormMethod.Get))
{
    <p>
        Search: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            Titre
        </th>
        <th>
            Durée
        </th>
        <th>
            Durée_Seconde
        </th>
        <th>
            Prix
        </th>
        <th>
            Extrait
        </th>
        <th>
            Titre de Composition
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Durée)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Durée_Seconde)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prix)
        </td>
        <td>
            @Html.Music(item.Extrait)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Composition.Titre_Composition)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.Code_Morceau }) 
        </td>
    </tr>
}

</table>

<br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))