SiteMarchand/Models/Musicien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteMarchand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musicien
    {
        public Musicien()
        {
            this.Composer = new HashSet<Composer>();
            this.Direction = new HashSet<Direction>();
            this.Interpréter = new HashSet<Interpréter>();
        }
    
        public int Code_Musicien { get; set; }
        public string Nom_Musicien { get; set; }
        public string Prénom_Musicien { get; set; }
        public Nullable<int> Année_Naissance { get; set; }
        public Nullable<int> Année_Mort { get; set; }
        public Nullable<int> Code_Pays { get; set; }
        public Nullable<int> Code_Genre { get; set; }
        public Nullable<int> Code_Instrument { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual ICollection<Composer> Composer { get; set; }
        public virtual ICollection<Direction> Direction { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Instrument Instrument { get; set; }
        public virtual ICollection<Interpréter> Interpréter { get; set; }
        public virtual Pays Pays { get; set; }
    }
}

SiteMarchand/Controllers/MusiciensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiteMarchand.Models;
using PagedList;

namespace SiteMarchand.Controllers
{

    // Controller Class
    public class MusiciensController : Controller
    {
        private Classique_WebEntities1 db = new Classique_WebEntities1();

        // GET: Musiciens
        public ActionResult Index(string searchString, string currentFilter, string sortOrder, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.FirstNameSortParm = String.IsNullOrEmpty(sortOrder) ? "firstname_desc" : "";
            ViewBag.BirthDateSortParm = sortOrder == "Date" ? "année_naissance_desc" : "Date";
            ViewBag.DeathDateSortParm = sortOrder == "Date" ? "année_mort_desc" : "Date";

            var compositeurs = db.Musicien.Include(c => c.Composer);

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            if (!String.IsNullOrEmpty(searchString))
            {
                compositeurs = db.Musicien.Include(c => c.Composer).Where(c => c.Nom_Musicien.StartsWith(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    compositeurs = compositeurs.OrderByDescending(s => s.Nom_Musicien);
                    break;
                case "firstname_desc":
                    compositeurs = compositeurs.OrderByDescending(s => s.Prénom_Musicien);
                    break;
                case "annee_naissance_desc":
                    compositeurs = compositeurs.OrderByDescending(s => s.Année_Naissance);
                    break;
                case "annee_mort_desc":
                    compositeurs = compositeurs.OrderByDescending(s => s.Année_Mort);
                    break;
                default:
                    compositeurs = compositeurs.OrderBy(s => s.Nom_Musicien);
                    break;
            }

            int pageSize = 25;
            int pageNumber = (page ?? 1);
            return View(compositeurs.ToPagedList(pageNumber, pageSize));
        }

        // GET: Musiciens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Musicien musicien = db.Musicien.Find(id);
            if (musicien == null)
            {
                return HttpNotFound();
            }
            else
            {
                ViewBag.Albums = getAlbums(musicien);
            }
            return View(musicien);
        }

        public List<Album> getAlbums(Musicien musicien)
        {   

            var albums = (from a in db.Album
                          join d in db.Disque on a.Code_Album equals d.Code_Album
                          join c in db.Composition_Disque on d.Code_Disque equals c.Code_Disque
                          join e in db.Enregistrement on c.Code_Morceau equals e.Code_Morceau
                          join m in db.Composition on e.Code_Composition equals m.Code_Composition
                          join co in db.Composition_Oeuvre on m.Code_Composition equals co.Code_Composition
                          join o in db.Oeuvre on co.Code_Oeuvre equals o.Code_Oeuvre
                          join comp in db.Composer on o.Code_Oeuvre equals comp.Code_Oeuvre
                          join mu in db.Musicien on comp.Code_Musicien equals mu.Code_Musicien
                          where mu.Code_Musicien == musicien.Code_Musicien
                          select a).Distinct();
            return albums.ToList();
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SiteMarchand/Views/Musiciens/Details.cshtml
@model SiteMarchand.Models.Musicien
@{
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Compositeur</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nom_Musicien)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Nom_Musicien)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Prénom_Musicien)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Prénom_Musicien)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Année_Naissance)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Année_Naissance)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Année_Mort)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Année_Mort)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Photo)
            </dt>
    
            <dd>
                @Html.Image(Model.Photo);
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Pays.Nom_Pays)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Pays.Nom_Pays)
            </dd>
    
        </dl>
    </div>
    <div>
        <table class="table">
            <tr>
                <th>
                    Titre
                </th>
                <th>
                    Année
                </th>
                <th>
                    Genre
                </th>
                <th>
                </th>
            </tr>
            @foreach (var item in ViewBag.Albums)
            {
                <tr>
                    <td>
                        @item.Titre_Album
                    </td>
                    <td>
                        @item.Année_Album
                    </td>
                    <td>
                        @item.Genre.Libellé_Abrégé
                    </td>
                    <td>
                        @Html.ActionLink("Details", "../Albums/Details", new { id = item.Code_Album })
                    </td>
                </tr>
            }
        </table>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Code_Musicien }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

SiteMarchand/Views/Musiciens/Index.cshtml
@model PagedList.IPagedList<SiteMarchand.Models.Musicien>

@using PagedList.Mvc;

@{
    ViewBag.Title = "Compositeurs";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <h2>Compositeurs</h2>

    @using (Html.BeginForm("Index", "Musiciens", FormMethod.Get))
    {
        <p>
            Search: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
    }
    
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
               @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.FirstNameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Birth Date", "Index", new { sortOrder = ViewBag.BirthDateSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Death Date", "Index", new { sortOrder = ViewBag.DeathDateSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                Photo
            </th>
            <th>
                Pays
            </th>
            <th></th>
        </tr>

    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom_Musicien)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prénom_Musicien)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Année_Naissance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Année_Mort)
            </td>
            <td>
                @Html.Image(item.Photo);
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pays.Nom_Pays)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.Code_Musicien }) 
            </td>
        </tr>
    }
    
    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</body>
</html>